local _, ns = ...
local L = LibStub("AceLocale-3.0"):GetLocale("MidnightRoutine", true)

local T, S, WQ, WD, DMF, TR, Ref = ns.T, ns.S, ns.WQ, ns.WD, ns.DMF, ns.TR, ns.Ref
local DRAGONFLIGHT_CATCHUP_ITEM_ID = ns.DRAGONFLIGHT_CATCHUP_ITEM_ID

local DRAGONFLIGHT_EXPANSION = {
        key = "dragonflight",
        label = L["ProfKnowledge_LegacySection_Dragonflight"] or "Dragonflight",
        sharedCatchupItemID = DRAGONFLIGHT_CATCHUP_ITEM_ID,
        professions = {
            { key = "alchemy", label = L["Alchemy"], skillLine = 2823, weekly = {
                TR{ spellID = 383522, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 75363, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75371, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77932, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77933, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66937, kp = 3, label = "Decaying News", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66938, kp = 3, label = "Mammoth Marrow", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66940, kp = 3, label = "Elixir Experiment", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72427, kp = 3, label = "Animated Infusion", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70530, kp = 3, label = "Examination Week", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70531, kp = 3, label = "Mana Markets", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70532, kp = 3, label = "Aiding the Raiding", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70533, kp = 3, label = "Draught, Oiled Again", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70289, kp = 3, zone = 2022, x = 25.1, y = 73.3, label = "Well-Insulated Mug", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70274, kp = 3, zone = 2022, x = 55.0, y = 81.0, label = "Frostforged Potion", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70305, kp = 3, zone = 2023, x = 79.2, y = 83.8, label = "Canteen of Suspicious Water", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70208, kp = 3, zone = 2024, x = 16.4, y = 38.5, label = "Experimental Decay Sample", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70309, kp = 3, zone = 2024, x = 67.0, y = 13.2, label = "Firewater Powder Sample", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70278, kp = 3, zone = 2025, x = 55.2, y = 30.5, label = "Tasty Candy", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70301, kp = 3, zone = 2025, x = 59.5, y = 38.4, label = "Contraband Concoction", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75649, kp = 3, zone = 2133, x = 62.10, y = 41.12, label = "Marrow-Ripened Slime", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75646, kp = 3, zone = 2133, x = 52.68, y = 18.30, label = "Nutrient Diluted Protofluid", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75651, kp = 3, zone = 2133, x = 40.48, y = 59.18, label = "Suspicious Mold", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Alchemist's Research", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Alchemist's Research", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Alchemist's Research", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "blacksmithing", label = L["Blacksmithing"], skillLine = 2822, weekly = {
                TR{ spellID = 383517, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70589, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75148, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75569, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77935, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77936, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66517, kp = 3, label = "A New Source of Weapons", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66897, kp = 3, label = "Fuel for the Forge", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66941, kp = 3, label = "Tremendous Tools", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72398, kp = 3, label = "Rock and Stone", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70211, kp = 3, label = "Stomping Explorers", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70233, kp = 3, label = "Axe Shortage", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70234, kp = 3, label = "All This Hammering", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70235, kp = 3, label = "Repair Bill", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70232, kp = 3, zone = 2022, x = 56.4, y = 19.5, label = "Glimmer of Blacksmithing Wisdom", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70246, kp = 3, zone = 2022, x = 22.0, y = 87.0, label = "Ancient Monument", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70312, kp = 3, zone = 2022, x = 65.5, y = 25.7, label = "Curious Ingots", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70296, kp = 3, zone = 2022, x = 35.5, y = 64.3, label = "Molten Ingot", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70310, kp = 3, zone = 2022, x = 34.5, y = 67.1, label = "Qalashi Weapon Diagram", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70313, kp = 3, zone = 2023, x = 81.1, y = 37.9, label = "Ancient Spear Shards", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70353, kp = 3, zone = 2023, x = 50.9, y = 66.5, label = "Falconer Gauntlet Drawings", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70314, kp = 3, zone = 2024, x = 53.1, y = 65.3, label = "Spelltouched Tongs", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70311, kp = 3, zone = 2025, x = 52.2, y = 80.5, label = "Draconic Flux", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76079, kp = 3, zone = 2133, x = 48.30, y = 21.95, label = "Brimstone Rescue Ring", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76078, kp = 3, zone = 2133, x = 57.15, y = 54.64, label = "Well-Worn Kiln", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76080, kp = 3, zone = 2133, x = 27.53, y = 42.87, label = "Zaqali Elder Spear", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Blacksmith's Diagrams", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Blacksmith's Diagrams", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Blacksmith's Diagrams", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "enchanting", label = L["Enchanting"], skillLine = 2825, weekly = {
                TR{ spellID = 383523, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 75150, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75865, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77910, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77937, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66884, kp = 3, label = "Fireproof Gear", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66900, kp = 3, label = "Enchanted Relics", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66935, kp = 3, label = "Crystal Quill Pens", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72423, kp = 3, label = "Weathering the Storm", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72155, kp = 3, label = "Spread the Enchantment", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72172, kp = 3, label = "Essence, Shards, and Chromatic Dust", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72173, kp = 3, label = "Braced for Enchantment", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72175, kp = 3, label = "A Secpt-acular Time", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70320, kp = 3, zone = 2022, x = 57.5, y = 83.6, label = "Flashfrozen Scroll", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70283, kp = 3, zone = 2022, x = 68.0, y = 26.8, label = "Lava-Infused Seed", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70272, kp = 3, zone = 2022, x = 57.5, y = 58.5, label = "Enchanted Debris", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70291, kp = 3, zone = 2023, x = 61.4, y = 67.6, label = "Stormbound Horn", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70336, kp = 3, zone = 2024, x = 38.5, y = 59.2, label = "Forgotten Arcane Tome", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70290, kp = 3, zone = 2024, x = 45.1, y = 61.2, label = "Faintly Enchanted Remains", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70298, kp = 3, zone = 2024, x = 21.0, y = 45.0, label = "Enriched Earthen Shard", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70342, kp = 3, zone = 2025, x = 59.9, y = 70.4, label = "Fractured Titanic Sphere", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75508, kp = 3, zone = 2133, x = 48.00, y = 17.00, label = "Lava-Drenched Shadow Crystal", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75510, kp = 3, zone = 2133, x = 36.66, y = 69.33, label = "Resonating Arcane Crystal", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75509, kp = 3, zone = 2133, x = 62.39, y = 53.80, label = "Shimmering Aqueous Orb", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Enchanter's Research", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Enchanter's Research", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Enchanter's Research", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "engineering", label = L["Engineering"], skillLine = 2827, weekly = {
                TR{ spellID = 383844, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70591, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75575, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75608, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77891, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77938, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66890, kp = 3, label = "Stolen Tools", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66891, kp = 3, label = "Explosive Ash", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66942, kp = 3, label = "Enemy Engineering", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72396, kp = 3, label = "Horns of Plenty", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70539, kp = 3, label = "And You Thought They Did Nothing", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70540, kp = 3, label = "An Engineer's Best Friend", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70545, kp = 3, label = "Blingtron 8000...?", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70557, kp = 3, label = "No Scopes", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70270, kp = 3, zone = 2022, x = 56.0, y = 44.9, label = "Boomthyr Rocket", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70275, kp = 3, zone = 2022, x = 49.09, y = 77.54, label = "Intact Coil Capacitor", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75186, kp = 3, zone = 2133, x = 37.82, y = 58.83, label = "Busted Wyrmhole Generator", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75184, kp = 3, zone = 2133, x = 50.51, y = 47.93, label = "Defective Survival Pack", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75431, kp = 3, zone = 2133, x = 49.44, y = 79.01, label = "Discarded Dracothyst Drill", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75430, kp = 3, zone = 2133, x = 57.65, y = 73.94, label = "Handful of Khaz'gorite Bolts", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75183, kp = 3, zone = 2133, x = 48.17, y = 27.93, label = "Haphazardly Discarded Bomb", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75188, kp = 3, zone = 2133, x = 49.87, y = 59.25, label = "Inconspicuous Data Miner", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75180, kp = 3, zone = 2133, x = 48.48, y = 48.64, label = "Misplaced Aberrus Outflow Blueprints", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75433, kp = 3, zone = 2133, x = 48.10, y = 16.59, label = "Overclocked Determination Core", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Engineer's Scribblings", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Engineer's Scribblings", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Engineer's Scribblings", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "herbalism", label = L["Herbalism"], skillLine = 2832, weekly = {
                TR{ spellID = 383515, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 71857, kp = 1, label = "Dreambloom Petal", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71858, kp = 1, label = "Dreambloom Petal", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71859, kp = 1, label = "Dreambloom Petal", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71860, kp = 1, label = "Dreambloom Petal", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71861, kp = 1, label = "Dreambloom Petal", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 71864, kp = 3, label = "Dreambloom", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 70613, kp = 3, label = "Get Their Bark Before They Bite", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70614, kp = 3, label = "Bubble Craze", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70615, kp = 3, label = "The Case of the Missing Herbs", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70616, kp = 3, label = "How Many??", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Herbalist's Notes", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Herbalist's Notes", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Herbalist's Notes", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "inscription", label = L["Inscription"], skillLine = 2828, weekly = {
                TR{ spellID = 383759, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70592, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75149, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75573, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77889, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77914, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66943, kp = 3, label = "Wood for Writing", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66944, kp = 3, label = "Peacock Pigments", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66945, kp = 3, label = "Icy Ink", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72438, kp = 3, label = "Tarasek Intentions", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70558, kp = 3, label = "Disillusioned Illusions", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70559, kp = 3, label = "Quill You Help?", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70560, kp = 3, label = "The Most Powerful Tool: Good Documentation", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70561, kp = 3, label = "A Scribe's Tragedy", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70306, kp = 3, zone = 2022, x = 67.87, y = 57.96, label = "Pulsing Earth Rune", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70307, kp = 3, zone = 2023, x = 85.7, y = 25.2, label = "Sign Language Reference Sheet", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70297, kp = 3, zone = 2024, x = 46.2, y = 23.9, label = "Dusty Darkmoon Card", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70293, kp = 3, zone = 2024, x = 43.7, y = 30.9, label = "Frosted Parchment", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70281, kp = 3, zone = 2112, x = 13.2, y = 63.68, label = "How to Train Your Whelpling", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70264, kp = 3, zone = 2025, x = 56.3, y = 41.2, label = "Forgetful Apprentice's Tome", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70248, kp = 3, zone = 2025, x = 47.24, y = 40.1, label = "Forgetful Apprentice's Tome", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70287, kp = 3, zone = 2025, x = 56.1, y = 40.9, label = "Counterfeit Darkmoon Deck", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76120, kp = 3, zone = 2133, x = 53.01, y = 74.27, label = "Hissing Rune Draft", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76121, kp = 3, zone = 2133, x = 54.57, y = 20.21, label = "Ancient Research", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76117, kp = 3, zone = 2133, x = 36.73, y = 46.32, label = "Intricate Zaqali Runes", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Scribe's Runic Drawings", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Scribe's Runic Drawings", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Scribe's Runic Drawings", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "jewelcrafting", label = L["Jewelcrafting"], skillLine = 2829, weekly = {
                TR{ spellID = 383524, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70593, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75362, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75602, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77892, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77912, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66516, kp = 3, label = "Mundane Gems, I Think Not!", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66949, kp = 3, label = "Trinket Bandits", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66950, kp = 3, label = "Heart of a Giant", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72428, kp = 3, label = "Hornswog Hoarders", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70562, kp = 3, label = "The Plumbers, Mason", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70563, kp = 3, label = "The Exhibition", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70564, kp = 3, label = "Spectacular", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70565, kp = 3, label = "Separation by Saturation", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70292, kp = 3, zone = 2022, x = 50.4, y = 45.1, label = "Closely Guarded Shiny", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70273, kp = 3, zone = 2022, x = 33.9, y = 63.7, label = "Igneous Gem", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70282, kp = 3, zone = 2023, x = 25.2, y = 35.4, label = "Lofty Malygite", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70263, kp = 3, zone = 2023, x = 61.8, y = 13.0, label = "Fragmented Key", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70277, kp = 3, zone = 2024, x = 45.0, y = 61.3, label = "Crystalline Overgrowth", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70271, kp = 3, zone = 2024, x = 44.6, y = 61.2, label = "Harmonic Crystal Harmonizer", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70285, kp = 3, zone = 2025, x = 59.8, y = 65.2, label = "Alexstraszite Cluster", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70261, kp = 3, zone = 2025, x = 56.91, y = 43.72, label = "Painter's Pretty Jewel", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75654, kp = 3, zone = 2133, x = 54.41, y = 32.47, label = "Broken Barter Boulder", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75653, kp = 3, zone = 2133, x = 34.47, y = 45.43, label = "Gently Jostled Jewels", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75652, kp = 3, zone = 2133, x = 40.37, y = 80.66, label = "Snubbed Snail Shells", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Jeweler's Illustrations", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Jeweler's Illustrations", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Jeweler's Illustrations", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "leatherworking", label = L["Leatherworking"], skillLine = 2830, weekly = {
                TR{ spellID = 383519, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70594, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75354, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75368, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77945, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77946, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66363, kp = 3, label = "Basilisk Bucklers", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66364, kp = 3, label = "To Fly a Kite", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66951, kp = 3, label = "Population Control", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72407, kp = 3, label = "Soaked in Success", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70567, kp = 3, label = "When You Give Bakar a Bone", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70568, kp = 3, label = "Tipping the Scales", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70569, kp = 3, label = "For Trisket, a Task Kit", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70571, kp = 3, label = "Drums Here!", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70308, kp = 3, zone = 2022, x = 39.0, y = 86.0, label = "Poacher's Pack", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70280, kp = 3, zone = 2022, x = 64.3, y = 25.4, label = "Spare Djaradin Tools", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70300, kp = 3, zone = 2023, x = 86.4, y = 53.7, label = "Wind-Blessed Hide", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70269, kp = 3, zone = 2024, x = 12.5, y = 49.4, label = "Well-Danced Drum", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70266, kp = 3, zone = 2024, x = 16.7, y = 38.8, label = "Decay-Infused Tanning Oil", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70286, kp = 3, zone = 2024, x = 57.5, y = 41.3, label = "Treated Hides", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70294, kp = 3, zone = 2025, x = 56.8, y = 30.5, label = "Decayed Scales", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75495, kp = 3, zone = 2133, x = 41.16, y = 48.81, label = "Flame-Infused Scale Oil", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75496, kp = 3, zone = 2133, x = 45.25, y = 21.12, label = "Lava-Forged Leatherworker's Knife", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 75502, kp = 3, zone = 2133, x = 49.56, y = 54.80, label = "Sulfur-Soaked Skins", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Leatherworker's Diagrams", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Leatherworker's Diagrams", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Leatherworker's Diagrams", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "mining", label = L["Mining"], skillLine = 2833, weekly = {
                TR{ spellID = 383516, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 72160, kp = 1, label = "Iridescent Ore Fragments", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72161, kp = 1, label = "Iridescent Ore Fragments", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72162, kp = 1, label = "Iridescent Ore Fragments", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72163, kp = 1, label = "Iridescent Ore Fragments", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72164, kp = 1, label = "Iridescent Ore Fragments", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 72165, kp = 3, label = "Iridescent Ore", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 70617, kp = 3, label = "All Mine, Mine, Mine", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70618, kp = 3, label = "The Call of the Forge", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72156, kp = 3, label = "A Fiery Flight", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72157, kp = 3, label = "The Weight of Earth", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Miner's Notes", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Miner's Notes", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Miner's Notes", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "skinning", label = L["Skinning"], skillLine = 2834, weekly = {
                TR{ spellID = 392944, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70381, kp = 1, label = "Curious Hide Scraps", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70383, kp = 1, label = "Curious Hide Scraps", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70384, kp = 1, label = "Curious Hide Scraps", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70385, kp = 1, label = "Curious Hide Scraps", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70386, kp = 1, label = "Curious Hide Scraps", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 70389, kp = 3, label = "Large Sample of Curious Hide", note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 70619, kp = 3, label = "A Study of Leather", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70620, kp = 3, label = "Scaling Up", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72158, kp = 3, label = "A Dense Delivery", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72159, kp = 3, label = "Scaling Down", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Skinner's Notes", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Skinner's Notes", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Skinner's Notes", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
            { key = "tailoring", label = L["Tailoring"], skillLine = 2831, weekly = {
                TR{ spellID = 383520, kp = 1, note = L["ProfKnowledge_TreatiseNote"] },
                WQ{ questID = 70595, kp = 2, note = L["ProfKnowledge_ServiceQuest"] },
                WQ{ questID = 75407, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 75600, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77947, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
                WQ{ questID = 77949, kp = 3, note = L["ProfKnowledge_WeeklyProfessionQuest"] },
            }, treasures = {
                T{ questID = 66899, kp = 3, label = "Fuzzy Legs", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66952, kp = 3, label = "The Gnoll's Clothes", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 66953, kp = 3, label = "All Things Fluffy", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 72410, kp = 3, label = "Pincers and Needles", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70572, kp = 3, label = "The Cold Does Bother Them, Actually", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70582, kp = 3, label = "Weave Well Enough Alone", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70586, kp = 3, label = "Sew Many Cooks", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70587, kp = 3, label = "A Knapsack Problem", note = L["ProfKnowledge_OneTimeProfessionQuest"] },
                T{ questID = 70302, kp = 3, zone = 2022, x = 74.7, y = 37.9, label = "Mysterious Banner", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70304, kp = 3, zone = 2022, x = 24.9, y = 69.7, label = "Itinerant Singed Fabric", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70295, kp = 3, zone = 2023, x = 35.34, y = 40.12, label = "Noteworthy Scrap of Carpet", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70303, kp = 3, zone = 2023, x = 66.1, y = 52.9, label = "Silky Surprise", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70284, kp = 3, zone = 2024, x = 16.2, y = 38.8, label = "Decaying Brackenhide Blanket", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70267, kp = 3, zone = 2024, x = 40.7, y = 54.5, label = "Intriguing Bolt of Blue Cloth", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70288, kp = 3, zone = 2025, x = 60.4, y = 79.7, label = "Miniature Bronze Dragonflight Banner", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 70372, kp = 3, zone = 2025, x = 58.6, y = 45.8, label = "Ancient Dragonweave Bolt", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76102, kp = 3, zone = 2133, x = 47.21, y = 48.55, label = "Abandoned Reserve Chute", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76116, kp = 3, zone = 2133, x = 44.52, y = 15.65, label = "Exquisitely Embroidered Banner", note = L["ProfKnowledge_TreasureNoteSkill25"] },
                T{ questID = 76110, kp = 3, zone = 2133, x = 59.11, y = 73.14, label = "Used Medical Wrap Kit", note = L["ProfKnowledge_TreasureNoteSkill25"] },
            }, books = {
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Dusty Tailor's Diagrams", note = "Rabul — Valdrakken (100 Artisan's Mettle, Preferred rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Rare Tailor's Diagrams", note = "Rabul — Valdrakken (150 Artisan's Mettle, Valued rep)" },
                Ref{ kp = 15, zone = 13862, x = 35.6, y = 59.0, label = "Ancient Tailor's Diagrams", note = "Rabul — Valdrakken (200 Artisan's Mettle, Esteemed rep)" },
            } },
        },
}

ns.RegisterLegacyExpansion(DRAGONFLIGHT_EXPANSION)
ns.RegisterProfessionWeeklyModules("dragonflight", DRAGONFLIGHT_EXPANSION.professions)
